version: "3.9"
services:
  api:
    build: ./backend
    container_name: cf-api
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - minio
    ports:
      - "8080:8080"

  web:
    build: ./frontend
    container_name: cf-web
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
    depends_on:
      - api
    ports:
      - "5173:5173"

  mongo:
    image: mongo:7
    container_name: cf-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio:latest
    container_name: cf-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=cf_minio
      - MINIO_ROOT_PASSWORD=cf_minio_secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  minio_data:
