services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build:
      context: ./backend
    environment:
      - APP_ENV=development
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=invoice_app
      - JWT_SECRET=dev-secret
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8080
    depends_on:
      - backend

volumes:
  mongo_data:


